# configuration file for TRAILS

dataset = "OMPS"
output_dir    = "/projekt1/remsens/work/jroschke/repositories/TRAILS/data/output/"
plot_dir      = "/projekt1/remsens/work/jroschke/data/Leipzig/Tropos/TRACE/leipzig/figures/"
traj_dir      = "/projekt7/remsens/data_new/site-campaign/leipzig-tropos/flexpart/2023/"
partposit_dir = "/projekt7/remsens/data_new/site-campaign/leipzig-tropos/flexpart/2023/" 

frp_dir = "/projekt1/remsens/work/jroschke/data/MODIS/"
omps_dir = "/projekt7/remsens/data_new/site-campaign/leipzig-tropos/suomi/nc/"
LCType_dir = "/projekt1/remsens/work/jroschke/data/"


[time]
    # dates to be processed
    begin = '2023-05-01'
    end   = '2023-07-31'
    # time step for which trajectories are calculated
    step = 3
    # duration of each trajectory
    tr_duration = -240

[flexpart]
    no_particles = 500
    rel_before_minutes = 5
    rel_after_minutes = 0
    rel_pm_height = 200
    species = 24
    outstep = 3


[height]
    top =  12000
    base = 500
    interval = 500
    

[station]
   name = 'Leipzig, Germany'
   short_name = 'leipzig'
   lat = 51.3397
   lon = 12.3731
   altitude = 113

