# configuration file for TRAILS


#output_dir    = "/path_to_/output/"
#plot_dir      = "/path_to_/figures/"
#traj_dir      = "/path_to_/flexpart_particle_positions/"
#partposit_dir = "/path_to_/flexpart_particle_positions/" 
#
#frp_dir       = "/path_to/MODIS_1Degree_daily_grids/"
#omps_dir      = "/path_to/OMPS_UVAI_1Degree_daily_grids/"
#LCType_dir    = "/path_to/land_surface_type_global_yearly_grids/"


output_dir    = "/projekt1/remsens/work/jroschke/data/Tawhaki/"
plot_dir      = "/projekt1/remsens/work/jroschke/data/Tawhaki/"
traj_dir      = "/projekt7/remsens/data_new/site-campaign/tawhaki/FLEXPART/"
partposit_dir = "/projekt7/remsens/data_new/site-campaign/tawhaki/FLEXPART/" 


omps_dir      = "/projekt7/remsens/data_new/site-campaign/leipzig-tropos/suomi/nc/2025/"

LCType_dir    = "/projekt1/remsens/work/jroschke/data/"

[time]
    # dates to be processed
    begin = '2025-10-22_00'
    end   = '2025-10-22_23'
    # time step for which trajectories are calculated
    step = 3
    # duration of each trajectory
    tr_duration = -240

[flexpart]
    no_particles = 500
    rel_before_minutes = 5
    rel_after_minutes = 0
    rel_pm_height = 200
    species = 24
    outstep = 3


[height]
    top =  15000
    base = 500
    interval = 500
    

[station]
    name = 'Tawhaki'
    short_name = 'tawhaki'
    lat =  -43.8279
    lon = 172.5378
    altitude = 5


