# configuration file for TRAILS


output_dir    = "/path_to_/output/"
plot_dir      = "/path_to_/figures/"
traj_dir      = "/path_to_/flexpart_particle_positions/"
partposit_dir = "/path_to_/flexpart_particle_positions/" 

frp_dir       = "/path_to/MODIS_1Degree_daily_grids/"
omps_dir      = "/path_to/OMPS_UVAI_1Degree_daily_grids/"
LCType_dir    = "/path_to/land_surface_type_global_yearly_grids/"

[time]
    # dates to be processed
    begin = 'YYYY-MM-DD'
    end   = 'YYYY-MM-DD'
    # time step for which trajectories are calculated
    step = 3
    # duration of each trajectory
    tr_duration = -240

[flexpart]
    no_particles = 500
    rel_before_minutes = 5
    rel_after_minutes = 0
    rel_pm_height = 200
    species = 24
    outstep = 3


[height]
    top =  12000
    base = 500
    interval = 500
    

[station]
   name = 'Leipzig, Germany'
   short_name = 'leipzig'
   lat = 51.3397
   lon = 12.3731
   altitude = 113

