

output_dir    = "/projekt1/remsens/work/jroschke/data/Invercargill/TRACE/"
plot_dir      = "/projekt1/remsens/work/jroschke/data/Invercargill/TRACE/invercargill/figures/"
traj_dir      = "/projekt7/remsens/data_new/site-campaign/invercargill/flexpart/"
partposit_dir = "/projekt7/remsens/data_new/site-campaign/invercargill/flexpart/" 


omps_dir      = "/projekt7/remsens/data_new/site-campaign/leipzig-tropos/suomi/nc/2025/"

LCType_dir    = "/projekt1/remsens/work/jroschke/data/"

[time]

    begin = '2025-09-02_00'
    end = '2025-09-03_00'
    # time step for which trajectories are calculated
    step = 3
    # duration of each trajectory
    tr_duration = -240

[flexpart]
    no_particles = 500
    rel_before_minutes = 5
    rel_after_minutes = 0
    rel_pm_height = 200
    species = 24
    outstep = 3

[hysplit]
    # terminate trajectory on contact with ground
    #terminate_ground = true
    terminate_ground = false


[plotmap]
    maptype = 'miller'
    #timeinterval = 6
    timeinterval = 24
    heights = []
    # heights = [8000.0, 10000.0, 11000.0]
    #bounds = [-179.9, 180.0, -75.0, 0.0]
    #bounds = [-120, 80, 0, 85]
    # default:
    #bounds = [-179.9, 180.0, -10.0, 88.0]
    # for the vulcano
    bounds = [-125.0, 45.0, 3.0, 40.0]
    # detailed map for paper
    #bounds = [-100, -50, -65, -20]
    centerlon = -10
    figsize=[10.0, 8.5]
    height_ratios = [7,1]

[height]
    #top = 18000
    base = 500
    interval = 500
    top = 15000
    plottop = 12250
    # 'md' mixing depth, '2.0' in km without
    reception = ['md', '2.0', '5.0', '8.0', '10.0']

[station]
    name = 'Invercargill'
    short_name = 'invercargill'
    lat =  -46.4174
    lon = 168.3307
    altitude = 2
